package com.example.summer.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.UUID;

@DynamoDBTable(tableName = "Slide")
@Data
public class Slide {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute
    private String link;

    @DynamoDBAttribute
    private User user;


}
