package com.example.summer.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.UUID;

@DynamoDBTable(tableName = "User")
@Data
public class User {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String password;
}
